name: Tests
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches: ["*"]
  pull_request:
    types: [merged]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        config:
          - ["3.9", "py39-plone60"]
          - ["3.10", "py310-plone60"]
          - ["3.11", "py311-plone60"]
    name: ${{ matrix.config[1] }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.config[0] }}
      - name: Pip cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            eggs
            .tox
          key: ${{ runner.os }}-pip-${{ matrix.config[0] }}-${{ hashFiles('setup.*', 'tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.config[0] }}-
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test
        run: tox -e ${{ matrix.config[1] }}
      - name: Upload coverage data to coveralls.io
        run: |
          pip install coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.config[1] }}
          COVERALLS_PARALLEL: true
    # - name: Upload coverage data to coveralls.io
    #   uses: coverallsapp/github-action@v2
    #   with:
    #     flag-name: run-${{ matrix.config[1] }}
    #     parallel: true

  coveralls_finish:
    needs: test
    # if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        run: |
          pip install --upgrade coveralls
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # uses: coverallsapp/github-action@v2
        # with:
        #   parallel-finished: true
